# Stage 1: Build the application
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

# Build arguments — public (baked into bundle)
ARG NEXT_PUBLIC_CLERK_SIGN_UP_URL
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
ARG NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
ARG NEXT_PUBLIC_LIVE_URL
ARG NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_SKIP_AUTH
ARG NEXT_PUBLIC_DEEPGRAM_API_KEY

# Build arguments — server-side / supabase deploy
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET_KEY
ARG SUPABASE_PROJECT_ID
ARG SUPABASE_SERVICE_ROLE_KEY
ARG SUPABASE_ACCESS_TOKEN
ARG DEEPGRAM_API_KEY
ARG DEEPGRAM_PROJECT_ID
ARG MISTRAL_API_KEY
ARG MISTRAL_MODEL
ARG SKIP_AUTH
ARG DREAMIT_URL
ARG DREAMIT_FOLOUP_SECRET
ARG DREAMIT_SUPABASE_SERVICE_ROLE_KEY

# Set environment variables for build
ENV NEXT_PUBLIC_CLERK_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_SIGN_UP_URL
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
ENV NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=$NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
ENV NEXT_PUBLIC_LIVE_URL=$NEXT_PUBLIC_LIVE_URL
ENV NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_SKIP_AUTH=$NEXT_PUBLIC_SKIP_AUTH
ENV NEXT_PUBLIC_DEEPGRAM_API_KEY=$NEXT_PUBLIC_DEEPGRAM_API_KEY
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET_KEY=$GOOGLE_CLIENT_SECRET_KEY
ENV SUPABASE_PROJECT_ID=$SUPABASE_PROJECT_ID
ENV SUPABASE_SERVICE_ROLE_KEY=$SUPABASE_SERVICE_ROLE_KEY
ENV SUPABASE_ACCESS_TOKEN=$SUPABASE_ACCESS_TOKEN
ENV DEEPGRAM_API_KEY=$DEEPGRAM_API_KEY
ENV DEEPGRAM_PROJECT_ID=$DEEPGRAM_PROJECT_ID
ENV MISTRAL_API_KEY=$MISTRAL_API_KEY
ENV MISTRAL_MODEL=$MISTRAL_MODEL
ENV SKIP_AUTH=$SKIP_AUTH
ENV DREAMIT_URL=$DREAMIT_URL
ENV DREAMIT_FOLOUP_SECRET=$DREAMIT_FOLOUP_SECRET
ENV DREAMIT_SUPABASE_SERVICE_ROLE_KEY=$DREAMIT_SUPABASE_SERVICE_ROLE_KEY
ENV CI=true

# Validate required environment variables
RUN if [ -z "$NEXT_PUBLIC_SUPABASE_URL" ] || [ -z "$NEXT_PUBLIC_SUPABASE_ANON_KEY" ]; then \
      echo "ERROR: NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY must be set" && \
      exit 1; \
    fi

RUN npx update-browserslist-db@latest || true

RUN yarn build || (echo "Build failed. Check the error above." && exit 1)

# Install Supabase CLI and link project
RUN apk add --no-cache curl
RUN curl -fsSL https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz \
  | tar -xz -C /usr/local/bin
RUN supabase link --project-ref $SUPABASE_PROJECT_ID

# Stage 2: Production image with Node.js (Next.js requires a Node server)
FROM node:20-alpine AS production

WORKDIR /app

ENV NODE_ENV=production
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

# standalone output includes its own minimal node_modules — no full copy needed
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/public ./public

EXPOSE 3000

RUN apk add --no-cache curl

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
  CMD curl -f http://localhost:3000/ || exit 1

CMD ["node", "server.js"]
